export const data = [
    // {
    //     firstName: "Sneha",
    //     email: "sneha@example.com",
    //     lastName: "Sharma",
    //     gender: "female",
    //     DOB: new Date("1995-08-15"),
    //     age: 27,
    //     interests: ["music", "books", "travel"],
    //     location: {
    //         type: "Point",
    //         coordinates: [72.8777, 19.076],
    //     },
    //     photos: "https://randomuser.me/api/portraits/women/3.jpg",
    //     sexualOrientation: ["female", "non-binary"],
    //     height: 165,
    //     score: 4.2,
    //     bio: "I'm a travel enthusiast who loves to explore new places and cultures. Looking for someone with similar interests.",
    //     likes: [],
    //     dislikes: [],
    //     mobileNo: 9876543210,
    //     ageRange: [25, 35],
    //     matches: 10,
    //     radius: 50,
    //     lookingFor: "relationship",
    // },
    // {
    //     firstName: "Aditya",
    //     email: "aditya@example.com",
    //     lastName: "Joshi",
    //     gender: "male",
    //     DOB: new Date("1990-05-28"),
    //     age: 31,
    //     interests: ["football", "movies", "reading"],
    //     location: {
    //         type: "Point",
    //         coordinates: [72.8777, 19.076],
    //     },
    //     photos: "https://randomuser.me/api/portraits/men/2.jpg",
    //     sexualOrientation: ["male", "genderqueer"],
    //     height: 180,
    //     score: 3.8,
    //     bio: "A football fanatic who also enjoys reading and watching movies. Looking for someone who shares similar interests.",
    //     likes: [],
    //     dislikes: [],
    //     mobileNo: 9876543211,
    //     ageRange: [25, 35],
    //     matches: 5,
    //     radius: 50,
    //     lookingFor: "casual",
    // },
    // {
    //     firstName: "Riya",
    //     email: "riya@example.com",
    //     lastName: "Gupta",
    //     gender: "female",
    //     DOB: new Date("1998-02-17"),
    //     age: 23,
    //     interests: ["photography", "music", "hiking"],
    //     location: {
    //         type: "Point",
    //         coordinates: [72.8777, 19.076],
    //     },
    //     photos: "https://randomuser.me/api/portraits/women/5.jpg",
    //     sexualOrientation: ["female", "agender"],
    //     height: 170,
    //     score: 4.5,
    //     bio: "I love exploring nature through hiking and photography. Looking for someone who appreciates nature and adventure.",
    //     likes: [],
    //     dislikes: [],
    //     mobileNo: 9876543212,
    //     ageRange: [20, 30],
    //     matches: 7,
    //     radius: 50,
    //     lookingFor: "relationship",
    // },
    // {
    //     firstName: 'Emma',
    //     email: 'emma123@gmail.com',
    //     lastName: 'Johnson',
    //     gender: 'female',
    //     DOB: new Date('1990-04-21'),
    //     age: 31,
    //     interests: ['photography', 'reading', 'hiking'],
    //     location: { type: 'Point', coordinates: [72.877655, 19.075983] },
    //     photos: 'https://randomuser.me/api/portraits/women/55.jpg',
    //     sexualOrientation: ['male', 'female', 'transgender'],
    //     height: 165,
    //     score: 8.5,
    //     bio: 'I am a nature lover and love to capture its beauty through my lens. Looking for someone who shares the same interests.',
    //     likes: [],
    //     dislikes: [],
    //     mobileNo: 9876543210,
    //     ageRange: [28, 35],
    //     matches: 3,
    //     radius: 10,
    //     lookingFor: 'casual'
    // },
    // {
    //     firstName: 'Noah',
    //     email: 'noah234@gmail.com',
    //     lastName: 'Clark',
    //     gender: 'male',
    //     DOB: new Date('1995-02-10'),
    //     age: 28,
    //     interests: ['cooking', 'fishing', 'football'],
    //     location: { type: 'Point', coordinates: [72.877655, 19.075983] },
    //     photos: 'https://randomuser.me/api/portraits/men/82.jpg',
    //     sexualOrientation: ['female'],
    //     height: 180,
    //     score: 7.2,
    //     bio: 'I am a foodie and love to experiment with different cuisines. Looking for someone who shares my passion for food.',
    //     likes: [],
    //     dislikes: [],
    //     mobileNo: 8765432109,
    //     ageRange: [25, 32],
    //     matches: 2,
    //     radius: 15,
    //     lookingFor: 'relationship'
    // },
    // {
    //     firstName: 'Olivia',
    //     email: 'olivia345@gmail.com',
    //     lastName: 'Brown',
    //     gender: 'female',
    //     DOB: new Date('1993-09-16'),
    //     age: 28,
    //     interests: ['dancing', 'traveling', 'yoga'],
    //     location: { type: 'Point', coordinates: [72.877655, 19.075983] },
    //     photos: 'https://randomuser.me/api/portraits/women/39.jpg',
    //     sexualOrientation: ['female', 'non-binary'],
    //     height: 170,
    //     score: 9.1,
    //     bio: 'I am a free-spirited person who loves to travel and explore new cultures. Looking for someone who can join me in my adventures.',
    //     likes: [],
    //     dislikes: [],
    //     mobileNo: 7654321098,
    //     ageRange: [25, 35],
    //     matches: 5,
    //     radius: 20,
    //     lookingFor: 'casual'
    // },
    // {
    //     firstName: "Pooja",
    //     email: "pooja@example.com",
    //     lastName: "Sharma",
    //     gender: "female",
    //     DOB: new Date("1992-08-25"),
    //     age: 29,
    //     interests: ["cooking", "reading", "traveling"],
    //     location: {
    //         type: "Point",
    //         coordinates: [72.8777, 19.076],
    //     },
    //     photos: "https://randomuser.me/api/portraits/women/1.jpg",
    //     sexualOrientation: ["male", "female", "non-binary"],
    //     height: 165,
    //     score: 4.5,
    //     bio: "I'm a fun-loving person who loves to travel and try new things!",
    //     likes: [],
    //     dislikes: [],
    //     mobileNo: 9876543210,
    //     ageRange: [25, 35],
    //     matches: 10,
    //     radius: 10,
    //     lookingFor: "casual"
    // },
    // {
    //     firstName: "Rahul",
    //     email: "rahul@example.com",
    //     lastName: "Patel",
    //     gender: "male",
    //     DOB: new Date("1990-02-10"),
    //     age: 32,
    //     interests: ["music", "photography", "sports"],
    //     location: {
    //         type: "Point",
    //         coordinates: [72.8258, 19.0144],
    //     },
    //     photos: "https://randomuser.me/api/portraits/men/2.jpg",
    //     sexualOrientation: ["female", "gender neutral", "two-spirit"],
    //     height: 178,
    //     score: 4.2,
    //     bio: "I'm a musician who loves to capture beautiful moments through my lens.",
    //     likes: [],
    //     dislikes: [],
    //     mobileNo: 9876543201,
    //     ageRange: [25, 35],
    //     matches: 20,
    //     radius: 20,
    //     lookingFor: "relationship"
    // },
    // {
    //     firstName: "temp",
    //     email: "temp@example.com",
    //     lastName: "user",
    //     gender: "female",
    //     DOB: new Date("1990-02-10"),
    //     age: 32,
    //     interests: ["music", "photography", "sports"],
    //     location: {
    //         type: "Point",
    //         coordinates: [72.8258, 19.0144],
    //     },
    //     photos: "https://randomuser.me/api/portraits/men/2.jpg",
    //     sexualOrientation: ["female", "gender neutral", "two-spirit"],
    //     height: 178,
    //     score: 4.2,
    //     bio: "I'm a musician who loves to capture beautiful moments through my lens.",
    //     likes: [],
    //     dislikes: [],
    //     mobileNo: 9876543201,
    //     ageRange: [25, 35],
    //     matches: 20,
    //     radius: 20,
    //     lookingFor: "relationship"
    // }
    // {
    //     firstName: "Jessica",
    //     email: "jessica@example.com",
    //     lastName: "Smith",
    //     gender: "female",
    //     DOB: new Date("1990-02-14"),
    //     age: 31,
    //     interests: ["traveling", "cooking", "hiking"],
    //     location: {
    //         type: "Point",
    //         coordinates: [72.8351, 19.075],
    //     },
    //     photos: "https://randomuser.me/api/portraits/women/44.jpg",
    //     sexualOrientation: ["female"],
    //     height: 170,
    //     score: 4.2,
    //     bio: "Hi, I'm Jessica! I'm a fun-loving person who loves to travel and try new things.",
    //     likes: [],
    //     dislikes: [],
    //     mobileNo: 9876543210,
    //     ageRange: [25, 40],
    //     matches: 5,
    //     radius: 50,
    //     lookingFor: "casual"
    // },
    // {
    //     firstName: "Amit",
    //     email: "amit@example.com",
    //     lastName: "Sharma",
    //     gender: "male",
    //     DOB: new Date("1988-08-10"),
    //     age: 33,
    //     interests: ["reading", "yoga", "movies"],
    //     location: {
    //         type: "Point",
    //         coordinates: [72.8699, 19.0908],
    //     },
    //     photos: "https://randomuser.me/api/portraits/men/72.jpg",
    //     sexualOrientation: ["male", "transgender"],
    //     height: 175,
    //     score: 3.8,
    //     bio: "I'm a quiet guy who enjoys reading and practicing yoga. Looking for someone who shares my interests.",
    //     likes: [],
    //     dislikes: [],
    //     mobileNo: 8765432109,
    //     ageRange: [25, 35],
    //     matches: 2,
    //     radius: 30,
    //     lookingFor: "relationship"
    // },
    // {
    //     firstName: "Priya",
    //     email: "priya@example.com",
    //     lastName: "Patel",
    //     gender: "female",
    //     DOB: new Date("1995-05-18"),
    //     age: 27,
    //     interests: ["painting", "music", "traveling"],
    //     location: {
    //         type: "Point",
    //         coordinates: [72.852, 19.0144],
    //     },
    //     photos: "https://randomuser.me/api/portraits/women/66.jpg",
    //     sexualOrientation: ["female", "non-binary"],
    //     height: 160,
    //     score: 4.5,
    //     bio: "I'm a creative person who loves to express myself through painting and music. Looking for someone who appreciates the arts.",
    //     likes: [],
    //     dislikes: [],
    //     mobileNo: 7654321098,
    //     ageRange: [25, 35],
    //     matches: 7,
    //     radius: 20,
    //     lookingFor: "relationship"
    // },
    // {
    //     firstName: "Samantha",
    //     email: "samantha@gmail.com",
    //     lastName: "Smith",
    //     gender: "Female",
    //     DOB: "1995-09-12",
    //     age: 27,
    //     interests: ["Traveling", "Photography", "Hiking"],
    //     location: {
    //         type: "Point",
    //         coordinates: [19.0760, 72.8777]
    //     },
    //     photos: "https://randomuser.me/api/portraits/women/47.jpg",
    //     sexualOrientation: ["Female", "Gender Neutral"],
    //     height: 165,
    //     score: 4.5,
    //     bio: "I'm a travel enthusiast and an aspiring photographer. Looking for someone who shares similar interests.",
    //     likes: [],
    //     dislikes: [],
    //     mobileNo: 9876543210,
    //     ageRange: [25, 35],
    //     matches: 10,
    //     radius: 50,
    //     lookingFor: "Casual"
    // },
    // {
    //     firstName: "Michael",
    //     email: "michael@gmail.com",
    //     lastName: "Jones",
    //     gender: "Male",
    //     DOB: "1990-03-18",
    //     age: 32,
    //     interests: ["Cooking", "Movies", "Football"],
    //     location: {
    //         type: "Point",
    //         coordinates: [19.0822, 72.7412]
    //     },
    //     photos: "https://randomuser.me/api/portraits/men/31.jpg",
    //     sexualOrientation: ["Male", "Transgender"],
    //     height: 180,
    //     score: 4.2,
    //     bio: "I'm a chef by profession and a huge movie buff. Looking for someone who loves good food and good movies.",
    //     likes: [],
    //     dislikes: [],
    //     mobileNo: 9876543210,
    //     ageRange: [25, 40],
    //     matches: 15,
    //     radius: 40,
    //     lookingFor: "Relationship"
    // },
    // {
    //     firstName: "Emily",
    //     email: "emily@gmail.com",
    //     lastName: "Johnson",
    //     gender: "Female",
    //     DOB: "1993-07-22",
    //     age: 29,
    //     interests: ["Dancing", "Music", "Shopping"],
    //     location: {
    //         type: "Point",
    //         coordinates: [19.0762, 72.8229]
    //     },
    //     photos: "https://randomuser.me/api/portraits/women/17.jpg",
    //     sexualOrientation: ["Female"],
    //     height: 170,
    //     score: 4.8,
    //     bio: "I'm a dancer and a fashion enthusiast. Looking for someone who loves to have fun and explore new things.",
    //     likes: [],
    //     dislikes: [],
    //     mobileNo: 9876543210,
    //     ageRange: [25, 35],
    //     matches: 20,
    //     radius: 30,
    //     lookingFor: "Casual"
    // },
    // {
    //     firstName: "tempuser2",
    //     email: "tempuser2@gmail.com",
    //     lastName: "Johnson",
    //     gender: "Female",
    //     DOB: "1993-07-22",
    //     age: 29,
    //     interests: ["Dancing", "Music", "Shopping"],
    //     location: {
    //         type: "Point",
    //         coordinates: [19.0762, 72.8229]
    //     },
    //     photos: "https://randomuser.me/api/portraits/women/17.jpg",
    //     sexualOrientation: ["Female"],
    //     height: 170,
    //     score: 4.8,
    //     bio: "I'm a dancer and a fashion enthusiast. Looking for someone who loves to have fun and explore new things.",
    //     likes: [],
    //     dislikes: [],
    //     mobileNo: 9876543210,
    //     ageRange: [25, 35],
    //     matches: 20,
    //     radius: 30,
    //     lookingFor: "Casual"
    // },
    {
        firstName: "Rachel",
        email: "rachel123@gmail.com",
        lastName: "Doe",
        gender: "female",
        DOB: new Date("1990-05-12"),
        age: 31,
        interests: ["reading", "traveling", "cooking"],
        location: {
            type: "Point",
            coordinates: [72.8777, 19.076],
        },
        photos: "https://randomuser.me/api/portraits/women/1.jpg",
        sexualOrientation: ["male", "female", "genderqueer"],
        height: 165,
        score: 4.5,
        bio: "I love reading books and exploring new places.",
        likes: [],
        dislikes: [],
        mobileNo: 9876543210,
        ageRange: [25, 40],
        matches: 10,
        radius: 50,
        lookingFor: "casual",
    },
    {
        firstName: "Siddharth",
        email: "siddharth1994@gmail.com",
        lastName: "Joshi",
        gender: "male",
        DOB: new Date("1994-02-15"),
        age: 29,
        interests: ["hiking", "music", "coding"],
        location: {
            type: "Point",
            coordinates: [72.8258, 19.0144],
        },
        photos: "https://randomuser.me/api/portraits/men/1.jpg",
        sexualOrientation: [
            "male",
            "transgender",
            "non-binary",
            "agender",
            "two-spirit",
        ],
        height: 180,
        score: 4.2,
        bio: "I am a software engineer who loves hiking and exploring new music.",
        likes: [],
        dislikes: [],
        mobileNo: 8765432109,
        ageRange: [24, 32],
        matches: 5,
        radius: 30,
        lookingFor: "relationship",
    },
    {
        "firstName": "Aria",
        "email": "aria.smith@gmail.com",
        "lastName": "Smith",
        "gender": "female",
        "DOB": "1995-12-01",
        "age": 27,
        "interests": [
            "reading",
            "hiking",
            "cooking"
        ],
        "location": {
            "type": "Point",
            "coordinates": [
                72.877656,
                19.076418
            ]
        },
        "photos": "https://randomuser.me/api/portraits/women/1.jpg",
        "sexualOrientation": [
            "lesbian",
            "pansexual"
        ],
        "height": 168,
        "score": 4.5,
        "bio": "I'm a passionate reader and love to explore new things in life. Looking for someone who shares similar interests and can be my partner in crime!",
        "likes": [],
        "dislikes": [],
        "mobileNo": 9876543210,
        "ageRange": [
            25,
            35
        ],
        "matches": 3,
        "radius": 50,
        "lookingFor": "relationship"
    },
    {
        "firstName": "Ethan",
        "email": "ethan.jackson@gmail.com",
        "lastName": "Jackson",
        "gender": "male",
        "DOB": "1991-09-24",
        "age": 31,
        "interests": [
            "football",
            "travelling",
            "music"
        ],
        "location": {
            "type": "Point",
            "coordinates": [
                72.825833,
                19.01441
            ]
        },
        "photos": "https://randomuser.me/api/portraits/men/2.jpg",
        "sexualOrientation": [
            "heterosexual"
        ],
        "height": 183,
        "score": 3.8,
        "bio": "I'm a football fan and love to travel to new places. Looking for someone who can be my partner in adventure!",
        "likes": [],
        "dislikes": [
        ],
        "mobileNo": 9876543211,
        "ageRange": [
            26,
            32
        ],
        "matches": 2,
        "radius": 30,
        "lookingFor": "casual"
    },
    {
        "firstName": "Sofia",
        "email": "sofia@test.com",
        "lastName": "Singh",
        "gender": "female",
        "DOB": "1990-02-01",
        "age": 32,
        "interests": [
            "Yoga",
            "Cooking",
            "Hiking"
        ],
        "location": {
            "type": "Point",
            "coordinates": [
                72.825833,
                19.01441
            ]
        },
        "photos": "https://randomuser.me/api/portraits/women/1.jpg",
        "sexualOrientation": [
            "female",
            "non-binary"
        ],
        "height": 170,
        "score": 8,
        "bio": "I love exploring new places and trying new foods. Looking for someone who shares my sense of adventure.",
        "likes": [],
        "dislikes": [],
        "mobileNo": 9876543210,
        "ageRange": [
            25,
            40
        ],
        "matches": 0,
        "radius": 50,
        "lookingFor": "casual"
    },
    {
        "firstName": "Aryan",
        "email": "aryan@test.com",
        "lastName": "Patel",
        "gender": "male",
        "DOB": "1985-08-15",
        "age": 37,
        "interests": [
            "Photography",
            "Reading",
            "Football"
        ],
        "location": {
            "type": "Point",
            "coordinates": [
                72.877656,
                19.075983
            ]
        },
        "photos": "https://randomuser.me/api/portraits/men/2.jpg",
        "sexualOrientation": [
            "male",
            "transgender"
        ],
        "height": 180,
        "score": 9,
        "bio": "I'm a big fan of nature and love taking pictures of landscapes. Looking for someone who shares my passion for the outdoors.",
        "likes": [],
        "dislikes": [],
        "mobileNo": 9988776655,
        "ageRange": [
            30,
            45
        ],
        "matches": 0,
        "radius": 30,
        "lookingFor": "relationship"
    },

]