export const data = [
    {
        firstName: "Sneha",
        email: "sneha@example.com",
        lastName: "Sharma",
        gender: "female",
        DOB: new Date("1995-08-15"),
        age: 27,
        interests: ["music", "books", "travel"],
        location: {
            type: "Point",
            coordinates: [72.8777, 19.076],
        },
        photos: "https://randomuser.me/api/portraits/women/3.jpg",
        sexualOrientation: ["female", "non-binary"],
        height: 165,
        score: 4.2,
        bio: "I'm a travel enthusiast who loves to explore new places and cultures. Looking for someone with similar interests.",
        likes: [],
        dislikes: [],
        mobileNo: 9876543210,
        ageRange: [25, 35],
        matches: 10,
        radius: 50,
        lookingFor: "relationship",
    },
    {
        firstName: "Aditya",
        email: "aditya@example.com",
        lastName: "Joshi",
        gender: "male",
        DOB: new Date("1990-05-28"),
        age: 31,
        interests: ["football", "movies", "reading"],
        location: {
            type: "Point",
            coordinates: [72.8777, 19.076],
        },
        photos: "https://randomuser.me/api/portraits/men/2.jpg",
        sexualOrientation: ["male", "genderqueer"],
        height: 180,
        score: 3.8,
        bio: "A football fanatic who also enjoys reading and watching movies. Looking for someone who shares similar interests.",
        likes: [],
        dislikes: [],
        mobileNo: 9876543211,
        ageRange: [25, 35],
        matches: 5,
        radius: 50,
        lookingFor: "casual",
    },
    {
        firstName: "Riya",
        email: "riya@example.com",
        lastName: "Gupta",
        gender: "female",
        DOB: new Date("1998-02-17"),
        age: 23,
        interests: ["photography", "music", "hiking"],
        location: {
            type: "Point",
            coordinates: [72.8777, 19.076],
        },
        photos: "https://randomuser.me/api/portraits/women/5.jpg",
        sexualOrientation: ["female", "agender"],
        height: 170,
        score: 4.5,
        bio: "I love exploring nature through hiking and photography. Looking for someone who appreciates nature and adventure.",
        likes: [],
        dislikes: [],
        mobileNo: 9876543212,
        ageRange: [20, 30],
        matches: 7,
        radius: 50,
        lookingFor: "relationship",
    },
    {
        firstName: 'Emma',
        email: 'emma123@gmail.com',
        lastName: 'Johnson',
        gender: 'female',
        DOB: new Date('1990-04-21'),
        age: 31,
        interests: ['photography', 'reading', 'hiking'],
        location: { type: 'Point', coordinates: [72.877655, 19.075983] },
        photos: 'https://randomuser.me/api/portraits/women/55.jpg',
        sexualOrientation: ['male', 'female', 'transgender'],
        height: 165,
        score: 8.5,
        bio: 'I am a nature lover and love to capture its beauty through my lens. Looking for someone who shares the same interests.',
        likes: [],
        dislikes: [],
        mobileNo: 9876543210,
        ageRange: [28, 35],
        matches: 3,
        radius: 10,
        lookingFor: 'casual'
    },
    {
        firstName: 'Noah',
        email: 'noah234@gmail.com',
        lastName: 'Clark',
        gender: 'male',
        DOB: new Date('1995-02-10'),
        age: 28,
        interests: ['cooking', 'fishing', 'football'],
        location: { type: 'Point', coordinates: [72.877655, 19.075983] },
        photos: 'https://randomuser.me/api/portraits/men/82.jpg',
        sexualOrientation: ['female'],
        height: 180,
        score: 7.2,
        bio: 'I am a foodie and love to experiment with different cuisines. Looking for someone who shares my passion for food.',
        likes: [],
        dislikes: [],
        mobileNo: 8765432109,
        ageRange: [25, 32],
        matches: 2,
        radius: 15,
        lookingFor: 'relationship'
    },
    {
        firstName: 'Olivia',
        email: 'olivia345@gmail.com',
        lastName: 'Brown',
        gender: 'female',
        DOB: new Date('1993-09-16'),
        age: 28,
        interests: ['dancing', 'traveling', 'yoga'],
        location: { type: 'Point', coordinates: [72.877655, 19.075983] },
        photos: 'https://randomuser.me/api/portraits/women/39.jpg',
        sexualOrientation: ['female', 'non-binary'],
        height: 170,
        score: 9.1,
        bio: 'I am a free-spirited person who loves to travel and explore new cultures. Looking for someone who can join me in my adventures.',
        likes: [],
        dislikes: [],
        mobileNo: 7654321098,
        ageRange: [25, 35],
        matches: 5,
        radius: 20,
        lookingFor: 'casual'
    },
    {
        firstName: "Pooja",
        email: "pooja@example.com",
        lastName: "Sharma",
        gender: "female",
        DOB: new Date("1992-08-25"),
        age: 29,
        interests: ["cooking", "reading", "traveling"],
        location: {
            type: "Point",
            coordinates: [72.8777, 19.076],
        },
        photos: "https://randomuser.me/api/portraits/women/1.jpg",
        sexualOrientation: ["male", "female", "non-binary"],
        height: 165,
        score: 4.5,
        bio: "I'm a fun-loving person who loves to travel and try new things!",
        likes: [],
        dislikes: [],
        mobileNo: 9876543210,
        ageRange: [25, 35],
        matches: 10,
        radius: 10,
        lookingFor: "casual"
    },
    {
        firstName: "Rahul",
        email: "rahul@example.com",
        lastName: "Patel",
        gender: "male",
        DOB: new Date("1990-02-10"),
        age: 32,
        interests: ["music", "photography", "sports"],
        location: {
            type: "Point",
            coordinates: [72.8258, 19.0144],
        },
        photos: "https://randomuser.me/api/portraits/men/2.jpg",
        sexualOrientation: ["female", "gender neutral", "two-spirit"],
        height: 178,
        score: 4.2,
        bio: "I'm a musician who loves to capture beautiful moments through my lens.",
        likes: [],
        dislikes: [],
        mobileNo: 9876543201,
        ageRange: [25, 35],
        matches: 20,
        radius: 20,
        lookingFor: "relationship"
    },
    {
        firstName: "temp",
        email: "temp@example.com",
        lastName: "user",
        gender: "female",
        DOB: new Date("1990-02-10"),
        age: 32,
        interests: ["music", "photography", "sports"],
        location: {
            type: "Point",
            coordinates: [72.8258, 19.0144],
        },
        photos: "https://randomuser.me/api/portraits/men/2.jpg",
        sexualOrientation: ["female", "gender neutral", "two-spirit"],
        height: 178,
        score: 4.2,
        bio: "I'm a musician who loves to capture beautiful moments through my lens.",
        likes: [],
        dislikes: [],
        mobileNo: 9876543201,
        ageRange: [25, 35],
        matches: 20,
        radius: 20,
        lookingFor: "relationship"
    }
]